# Generated by Django 5.2.8 on 2025-11-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Administrator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_name", models.CharField(max_length=30)),
                ("admin_email", models.CharField(max_length=30)),
                ("admin_password", models.CharField(max_length=30)),
            ],
        ),
    ]
