# Generated by Django 5.2.8 on 2025-11-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Administrator", "0004_tbl_place"),
    ]

    operations = [
        migrations.DeleteModel(
            name="tbl_place",
        ),
    ]
