# Generated by Django 5.2.8 on 2025-11-10 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Administrator", "0005_delete_tbl_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_name", models.CharField(max_length=30)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Administrator.tbl_district",
                    ),
                ),
            ],
        ),
    ]
