# Generated by Django 5.2.8 on 2025-11-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Administrator", "0006_tbl_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=30)),
            ],
        ),
    ]
