# Generated by Django 5.2.11 on 2026-02-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0008_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_name', models.CharField(max_length=30)),
            ],
        ),
    ]
