# Generated by Django 5.2.11 on 2026-02-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0009_tbl_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_sports',
            name='required_players',
            field=models.IntegerField(default=1),
        ),
    ]
