# Generated by Django 5.2.10 on 2026-01-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TurfOwner', '0002_tbl_package_tbl_slot_delete_tbl_sports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_slot',
            name='turf',
        ),
        migrations.DeleteModel(
            name='tbl_package',
        ),
        migrations.DeleteModel(
            name='tbl_slot',
        ),
    ]
