# Generated by Django 5.2.10 on 2026-01-29 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0011_tbl_sports_tbl_turfregistration'),
        ('TurfOwner', '0003_remove_tbl_slot_turf_delete_tbl_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_details', models.CharField(max_length=50)),
                ('package_price', models.FloatField()),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_turfregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_details', models.CharField(max_length=50)),
                ('slot_time', models.TimeField()),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_turfregistration')),
            ],
        ),
    ]
