# Generated by Django 5.2.9 on 2026-02-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TurfOwner', '0005_tbl_mysports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_mysports',
        ),
    ]
