# Generated by Django 5.2.9 on 2026-02-02 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_tbl_sports_tbl_turfregistration'),
        ('TurfOwner', '0006_delete_tbl_mysports'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_turfsports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_sports')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_turfregistration')),
            ],
        ),
    ]
