# Generated by Django 5.2.11 on 2026-02-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TurfOwner', '0007_tbl_turfsports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_slot',
            name='turf',
        ),
        migrations.RemoveField(
            model_name='tbl_turfsports',
            name='sports',
        ),
        migrations.RemoveField(
            model_name='tbl_turfsports',
            name='turf',
        ),
        migrations.DeleteModel(
            name='tbl_package',
        ),
        migrations.DeleteModel(
            name='tbl_slot',
        ),
        migrations.DeleteModel(
            name='tbl_turfsports',
        ),
    ]
