# Generated by Django 5.2.11 on 2026-02-25 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0014_initial'),
        ('TurfOwner', '0008_remove_tbl_slot_turf_remove_tbl_turfsports_sports_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_details', models.CharField(max_length=50)),
                ('package_price', models.FloatField()),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_turf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_details', models.CharField(max_length=50)),
                ('slot_time', models.TimeField()),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_turf')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_turfsports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_sports')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_turf')),
            ],
        ),
    ]
