# Generated by Django 5.2.11 on 2026-02-25 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0008_delete_tbl_user'),
        ('Guest', '0017_remove_tbl_turf_place'),
        ('TurfOwner', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=100)),
                ('turf_description', models.CharField(max_length=200)),
                ('turf_capacity', models.IntegerField()),
                ('turf_price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('turf_image', models.FileField(upload_to='Assets/Turf/')),
                ('turf_contact_number', models.CharField(max_length=15)),
                ('turf_status', models.IntegerField(default=0)),
                ('truf_doj', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_owner')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_package',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurfOwner.tbl_turf'),
        ),
        migrations.AlterField(
            model_name='tbl_slot',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurfOwner.tbl_turf'),
        ),
        migrations.AlterField(
            model_name='tbl_turfsports',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurfOwner.tbl_turf'),
        ),
    ]
