# Generated by Django 5.2.11 on 2026-02-25 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0018_delete_tbl_turf'),
        ('TurfOwner', '0010_tbl_turf_alter_tbl_package_turf_alter_tbl_slot_turf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_turf_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.FileField(upload_to='Assets/TurfGallery/')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurfOwner.tbl_turf')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_turf_sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_sports')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurfOwner.tbl_turf')),
            ],
        ),
    ]
