# Generated by Django 5.2.11 on 2026-02-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TurfOwner', '0011_tbl_turf_gallery_tbl_turf_sports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_turf',
            name='turf_price_per_hour',
        ),
    ]
