# Generated by Django 5.2.11 on 2026-02-25 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurfOwner', '0013_remove_tbl_slot_turf_remove_tbl_turfsports_sports_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.CharField(max_length=50)),
                ('slot_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurfOwner.tbl_turf')),
            ],
        ),
    ]
