# Generated by Django 5.2.11 on 2026-02-25 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0009_tbl_sports'),
        ('TurfOwner', '0014_tbl_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_turf_sports',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_sports'),
        ),
    ]
