# Generated by Django 5.2.11 on 2026-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurfOwner', '0015_alter_tbl_turf_sports_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_slot',
            name='slot_time',
        ),
        migrations.AddField(
            model_name='tbl_slot',
            name='slot_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_slot',
            name='slot_start_time',
            field=models.TimeField(null=True),
        ),
    ]
