# Generated by Django 5.2.8 on 2025-11-21 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Administrator", "0007_tbl_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_userregistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=30)),
                ("user_email", models.CharField(max_length=30)),
                ("user_password", models.CharField(max_length=30)),
                ("user_contact", models.CharField(max_length=30)),
                ("user_dob", models.DateField()),
                ("user_photo", models.FileField(upload_to="Assets/UserDocs/")),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Administrator.tbl_place",
                    ),
                ),
            ],
        ),
    ]
