# Generated by Django 5.2.8 on 2025-11-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="tbl_userregistration",
        ),
    ]
