# Generated by Django 5.2.8 on 2025-11-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_email", models.CharField(max_length=30)),
                ("login_password", models.CharField(max_length=30)),
            ],
        ),
    ]
