# Generated by Django 5.2.8 on 2025-11-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0004_tbl_login"),
    ]

    operations = [
        migrations.DeleteModel(
            name="tbl_login",
        ),
    ]
