# Generated by Django 5.2.8 on 2025-12-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_delete_tbl_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_turfregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turfregistration_name', models.CharField(max_length=30)),
                ('turfregistration_email', models.CharField(max_length=30)),
                ('turfregistration_contact', models.CharField(max_length=30)),
                ('turfregistration_address', models.CharField(max_length=30)),
                ('turfregistration_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('turfregistration_proof', models.FileField(upload_to='Assets/UserDocs/')),
                ('turfregistration_capacity', models.CharField(max_length=30)),
                ('turfregistration_password', models.CharField(max_length=30)),
            ],
        ),
    ]
