# Generated by Django 5.2.8 on 2025-12-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_turfregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_turfregistration',
        ),
    ]
