# Generated by Django 5.2.8 on 2025-12-02 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0008_delete_tbl_user'),
        ('Guest', '0007_delete_tbl_turfregistration'),
        ('TurfOwner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_turfregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turfregistration_name', models.CharField(max_length=30)),
                ('turfregistration_email', models.CharField(max_length=30)),
                ('turfregistration_contact', models.CharField(max_length=30)),
                ('turfregistration_address', models.CharField(max_length=30)),
                ('turfregistration_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('turfregistration_proof', models.FileField(upload_to='Assets/UserDocs/')),
                ('turfregistration_capacity', models.CharField(max_length=30)),
                ('turfregistration_password', models.CharField(max_length=30)),
                ('turfregistration_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurfOwner.tbl_sports')),
            ],
        ),
    ]
