# Generated by Django 5.2.10 on 2026-01-29 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_turfregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_turfregistration',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_sports'),
        ),
    ]
