# Generated by Django 5.2.10 on 2026-01-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_sports_alter_tbl_turfregistration_sport'),
        ('TurfOwner', '0003_remove_tbl_slot_turf_delete_tbl_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_turfregistration',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='tbl_turfregistration',
            name='place',
        ),
        migrations.DeleteModel(
            name='tbl_sports',
        ),
        migrations.DeleteModel(
            name='tbl_turfregistration',
        ),
    ]
