# Generated by Django 5.2.11 on 2026-02-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0008_delete_tbl_user'),
        ('Guest', '0011_tbl_sports_tbl_turfregistration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_turfregistration',
            new_name='tbl_turf',
        ),
        migrations.RenameModel(
            old_name='tbl_userregistration',
            new_name='tbl_user',
        ),
    ]
