# Generated by Django 5.2.11 on 2026-02-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_rename_tbl_turfregistration_tbl_turf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_turf',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='tbl_turf',
            name='place',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='place',
        ),
        migrations.DeleteModel(
            name='tbl_sports',
        ),
        migrations.DeleteModel(
            name='tbl_turf',
        ),
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
