# Generated by Django 5.2.11 on 2026-02-25 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0008_delete_tbl_user'),
        ('Guest', '0013_remove_tbl_turf_sport_remove_tbl_turf_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=30)),
                ('turf_email', models.CharField(max_length=30)),
                ('turf_contact', models.CharField(max_length=30)),
                ('turf_address', models.CharField(max_length=30)),
                ('turf_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('turf_proof', models.FileField(upload_to='Assets/UserDocs/')),
                ('turf_capacity', models.CharField(max_length=30)),
                ('turf_password', models.CharField(max_length=30)),
                ('turf_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_sports')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=30)),
                ('user_contact', models.CharField(max_length=30)),
                ('user_dob', models.DateField()),
                ('user_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
