# Generated by Django 5.2.11 on 2026-02-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0014_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_turf',
            name='sport',
        ),
    ]
