# Generated by Django 5.2.11 on 2026-02-25 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0008_delete_tbl_user'),
        ('Guest', '0015_remove_tbl_turf_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_email', models.CharField(max_length=100)),
                ('owner_password', models.CharField(max_length=100)),
                ('owner_phone', models.CharField(max_length=15)),
                ('owner_address', models.CharField(max_length=200)),
                ('owner_photo', models.FileField(upload_to='Assets/OwnerDocs/')),
                ('owner_proof', models.FileField(upload_to='Assets/OwnerDocs/')),
                ('owner_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
