# Generated by Django 5.2.11 on 2026-02-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0016_tbl_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_turf',
            name='place',
        ),
    ]
