# Generated by Django 5.2.11 on 2026-02-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0017_remove_tbl_turf_place'),
        ('TurfOwner', '0010_tbl_turf_alter_tbl_package_turf_alter_tbl_slot_turf_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_turf',
        ),
    ]
