# Generated by Django 5.2.11 on 2026-02-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0018_delete_tbl_turf'),
        ('TurfOwner', '0015_alter_tbl_turf_sports_sport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_sports',
        ),
    ]
