# Generated by Django 5.2.9 on 2026-02-02 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0011_tbl_sports_tbl_turfregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_sport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_sports')),
            ],
        ),
    ]
