# Generated by Django 5.2.9 on 2026-02-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_booking',
        ),
    ]
