# Generated by Django 5.2.9 on 2026-02-05 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_tbl_sports_tbl_turfregistration'),
        ('User', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='sports',
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_name', models.CharField(max_length=30)),
                ('complaint_content', models.CharField(max_length=30)),
                ('complaint_reply', models.CharField(max_length=30)),
                ('complaint_date', models.DateField()),
                ('user_name', models.CharField(max_length=30)),
                ('turf_name', models.CharField(max_length=30)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_turfregistration')),
            ],
        ),
    ]
