# Generated by Django 5.2.9 on 2026-02-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_tbl_booking_sports_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
