# Generated by Django 5.2.9 on 2026-02-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(max_length=30)),
                ('request_date', models.DateField()),
            ],
        ),
    ]
