# Generated by Django 5.2.9 on 2026-02-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_content', models.CharField(max_length=100)),
                ('rating_date', models.DateField()),
            ],
        ),
    ]
