# Generated by Django 5.2.11 on 2026-02-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_tbl_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_rating',
        ),
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
