# Generated by Django 5.2.11 on 2026-02-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_booking',
        ),
    ]
