# Generated by Django 5.2.11 on 2026-02-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='booking_players',
            field=models.IntegerField(default=1),
        ),
    ]
