# Generated by Django 5.2.11 on 2026-02-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_tbl_booking_booking_players'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_booking',
        ),
    ]
