# Generated by Django 5.2.11 on 2026-02-25 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0019_delete_tbl_sports'),
        ('TurfOwner', '0015_alter_tbl_turf_sports_sport'),
        ('User', '0014_delete_tbl_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_todate', models.DateField()),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking_status', models.IntegerField(default=0)),
                ('booking_players', models.IntegerField(default=1)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurfOwner.tbl_slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
