# Generated by Django 5.2.11 on 2026-02-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
