# Generated by Django 5.2.11 on 2026-02-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_alter_tbl_booking_booking_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_booking',
        ),
    ]
