# Generated by Django 5.2.11 on 2026-02-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0010_tbl_sports_required_players'),
        ('Guest', '0019_delete_tbl_sports'),
        ('TurfOwner', '0015_alter_tbl_turf_sports_sport'),
        ('User', '0018_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_players', models.IntegerField()),
                ('joined_players', models.IntegerField(default=0)),
                ('request_description', models.CharField(max_length=200)),
                ('request_status', models.IntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurfOwner.tbl_slot')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_sports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_request_join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
