# Generated by Django 5.2.11 on 2026-02-27 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0019_delete_tbl_sports'),
        ('TurfOwner', '0015_alter_tbl_turf_sports_sport'),
        ('User', '0019_tbl_request_tbl_request_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_data', models.IntegerField()),
                ('user_review', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurfOwner.tbl_turf')),
            ],
        ),
    ]
