# Generated by Django 5.2.11 on 2026-02-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_tbl_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_rating',
            old_name='vehicle',
            new_name='truf',
        ),
    ]
