# Generated by Django 5.2.11 on 2026-02-27 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0019_delete_tbl_sports'),
        ('User', '0021_rename_vehicle_tbl_rating_truf'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=100)),
                ('complaint_content', models.CharField(max_length=500)),
                ('complaint_status', models.IntegerField(default=0)),
                ('complaint_date', models.DateTimeField(auto_now_add=True)),
                ('complaint_reply', models.CharField(max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
