# Generated by Django 5.2.11 on 2026-03-02 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0019_delete_tbl_sports'),
        ('User', '0023_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_reason', models.CharField(max_length=200)),
                ('refund_status', models.IntegerField(default=0)),
                ('refund_date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
